#!/bin/bash

#case $1 in
#	1) notify-send "cpu"; exit ;;
#esac

#temp=$(< /sys/class/thermal/thermal_zone0/device/thermal_zone/temp)
temp=$(sensors | awk '/Core 0/ {print "" $3}')
[ "$temp" == "" ] && exit
printf " %sC" "$(echo "$temp" | grep -o -E '[0-9]+' | head -1)"
