#!/bin/bash

case $1 in 
	1) setsid -f "urxvt" -e sh -c "newsboat && pkill -RTMIN+8 dwmblocks"; exit ;; 
	3) notify-send "News Boat" "Updating"  && newsboat -x reload && notify-send "News Boat" "Updated" && pkill -RTMIN+8 dwmblocks; exit;;
esac

output=$(newsboat -x print-unread | awk '{ print $1 }')
[ "$(echo $output | cut -d\  -f1-1)" == "Failed" ] && exit

printf "%s%s" "M" "$output"
