#!/bin/bash

# emoji support requires ttf-font-awesome 5.15.3-1

[ "$(cat /sys/class/dmi/id/chassis_type)" == "3" ] && exit

case $1 in
	1) notify-send "Battery Status" "Battery Status Information
: plugged in
: no battery
: battery charging
: battery full
: battery discharging"
exit 0;;

esac

plug=""
noBattery=""
fullBattery=""
chargBattery=""
disBattery=""

# Test for wall outlet plugin
[ -d /sys/class/power_supply/AC/ ] && ac="$( cat /sys/class/power_supply/AC/online )"
[ -d /sys/class/power_supply/ACAD/ ] && ac="$( cat /sys/class/power_supply/ACAD/online )"
if [ $ac = "1" ]
then
	acOutput=$plug
else
	acOutput=""
fi

# Test for battery plug in
[ -d /sys/class/power_supply/BAT0 ] && bat="BAT0"
[ -d /sys/class/power_supply/BAT1 ] && bat="BAT1"
bat="BAT1"

if [ "$bat" != "" ]
then
	# battery plugged in
	batcapacity="$( cat /sys/class/power_supply/$bat/capacity)"
	batstatus="$( cat /sys/class/power_supply/$bat/status)"	
	case "$batstatus" in
		"Full") batOutput=$fullBattery ;;
		"Charging") batOutput=$chargBattery ;;
		"Discharging") batOutput=$disBattery ;;
	esac
	#[ $batstatus == "Full" ] && batOutput=$fullBattery
	#[ $batstatus == "Charging" ] && batOutput=$chargBattery
	#[ $batstatus == "Discharging" ] && batOutput=$disBattery
fi

printf "%s %s %s" "$acOutput" "$batOutput" "$batcapacity%"
sleep 0.1
